[package]
name = "custom_io_rpi_gpio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rplc = "0.3.0"
rppal = "0.14.1"

[build-dependencies]
rplc = "0.3.0"
