core: EVA ICS node core
svc: System controller service

core <- svc

agent1: Linux agent
agent2: Linux agent
agent3: Windows agent
agent4: Windows agent

svc <- agent1
svc <- agent2
svc <- agent3
svc <- agent4
